### PR TITLE
Some fixes for Linux v6.6

### PR DESCRIPTION
**Pull request by dangowrt**
Add lots of missing symbols, adjust for renamed or replaced symbols. Fix fitblk and mtk_eth_soc driver build.

### CODE REVIEW

**Comment by hackpascal** [comment]
thx.

I'm fixing compilation errors for wireless drivers. I'll merge this later.

**Comment by dangowrt** [comment]
Nice. We also discussed to maybe drop `compat-wireless` and just package wireless drivers from Linux tree now that we are relatively close to upstream Linux. But if you manage to get backports-6.6 build on top of actual Linux 6.6 that would be even better, as it would allow to have newer wireless drivers in future without having to backport patch-by-patch.

PS: I'm preparing the mediatek target for Linux 6.6 right now, wasted too much time on trying to cleanly fix that outdated out-of-tree realtek driver (and decided to now just add some casts to fix build, it's ugly anyway).

**Comment by hackpascal** [comment]
> But if you manage to get backports-6.6 build on top of actual Linux 6.6 that would be even better

I've already made it built successfully XD.

Also, rtl8812au-ct has also been fixed.

**Comment by robimarko** [comment]
@dangowrt But that would mean different WLAN features for each kernel, and how would one maintain that?

@hackpascal You managed to fix those genetlink userhdr errors?

**Comment by hackpascal** [comment]
> @hackpascal You managed to fix those genetlink userhdr errors?

Yes. But not tested yet.

**Comment by robimarko** [comment]
> > @hackpascal You managed to fix those genetlink userhdr errors?
> 
> Yes. But not tested yet.

Can you post the fix, I started fixing it late last night but was too tired at the end.

**Comment by hackpascal** [comment]
> Can you post the fix, I started fixing it late last night but was too tired at the end.

I'll push fixes later today

**Comment by hackpascal** [comment]
> > > @hackpascal You managed to fix those genetlink userhdr errors?
> > 
> > 
> > Yes. But not tested yet.
> 
> Can you post the fix, I started fixing it late last night but was too tired at the end.

updated

**Comment by hackpascal** [comment]
@dangowrt Thanks. I'll reorganize these patches in next update.
